services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: typing-enhanced-server
    user: "1000:1000"
    ports:
      - "8787:8787"
    volumes:
      # Mount source code for hot reload
      - ./server:/app
      - /app/node_modules
      - ~/.config/.wrangler:/home/bun/.config/.wrangler
    environment:
      - NODE_ENV=development
    networks:
      - typing-enhanced-network # http://server:8787 have to use this in client env

  client:
    build:
      context: ./client/next-app
      dockerfile: Dockerfile
    container_name: typing-enhanced-client
    user: "1000:1000"
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./client/next-app:/app
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - typing-enhanced-network # http://client:3000
    depends_on:
      - server

networks:
  typing-enhanced-network:
    driver: bridge
